#pragma once
#include "Blam/Cache/DataTypes/StringID.h"
#include "Blam/Math/real_math.h"

#define HS_SYNC_TABLE_SIZE 16
#define HS_SENT_BUFFER_SIZE 128

namespace hs
{
	enum class e_hs_type : WORD 
	{
		unparsed,
		special_form,
		function_name,
		passthrough,
		nothing,
		boolean,
		real,
		hs_short,
		hs_long,
		string,
		script,
		string_id,
		unit_seat_mapping,
		trigger_volume,
		cutscene_flag,
		cutscene_camera_point,
		cutscene_title,
		cutscene_recording,
		device_group,
		ai,
		ai_command_list,
		ai_command_script,
		ai_behavior,
		ai_orders,
		starting_profile,
		conversation,
		structure_bsp,
		navpoint,
		point_reference,
		style,
		hud_message,
		object_list,
		sound,
		effect,
		damage,
		looping_sound,
		animation_graph,
		damage_effect,
		object_definition,
		bitmap,
		shader,
		render_model,
		structure_definition,
		lightmap_definition,
		game_difficulty,
		team,
		actor_type,
		hud_corner,
		model_state,
		network_event,
		// objects
		object,
		unit,
		vehicle,
		weapon,
		device,
		scenery,
		object_name,
		unit_name,
		vehicle_name,
		weapon_name,
		device_name,
		scenery_name
	};

	struct s_hs_type_string
	{
		e_hs_type hs_type;
		std::string hs_type_string;
	};

	static s_hs_type_string hs_type_string[] 
	{
		{ e_hs_type::unparsed,	"unparsed" },
		{ e_hs_type::special_form,	"special form" },
		{ e_hs_type::function_name,	"function name" },
		{ e_hs_type::passthrough,	"passthrough" },
		{ e_hs_type::nothing,	"void" },
		{ e_hs_type::boolean,	"boolean" },
		{ e_hs_type::real,	"real" },
		{ e_hs_type::hs_short,	"short" },
		{ e_hs_type::hs_long,	"long" },
		{ e_hs_type::string,	"string" },
		{ e_hs_type::script,	"script" },
		{ e_hs_type::string_id,	"string_id" },
		{ e_hs_type::unit_seat_mapping,	"unit_seat_mapping" },
		{ e_hs_type::trigger_volume,	"trigger_volume" },
		{ e_hs_type::cutscene_flag,	"cutscene_flag" },
		{ e_hs_type::cutscene_camera_point,	"cutscene_camera_point" },
		{ e_hs_type::cutscene_title,	"cutscene_title" },
		{ e_hs_type::cutscene_recording,	"cutscene_recording" },
		{ e_hs_type::device_group,	"device_group" },
		{ e_hs_type::ai,	"ai" },
		{ e_hs_type::ai_command_list,	"ai_command_list" },
		{ e_hs_type::ai_command_script,	"ai_command_script" },
		{ e_hs_type::ai_behavior,	"ai_behavior" },
		{ e_hs_type::ai_orders,	"ai_orders" },
		{ e_hs_type::starting_profile,	"starting_profile" },
		{ e_hs_type::conversation,	"conversation" },
		{ e_hs_type::structure_bsp,	"structure_bsp" },
		{ e_hs_type::navpoint,	"navpoint" },
		{ e_hs_type::point_reference,	"point reference" },
		{ e_hs_type::style,	"style" },
		{ e_hs_type::hud_message,	"hud_message" },
		{ e_hs_type::object_list,	"object_list" },
		{ e_hs_type::sound,	"sound" },
		{ e_hs_type::effect,	"effect" },
		{ e_hs_type::damage,	"damage" },
		{ e_hs_type::looping_sound,	"looping_sound" },
		{ e_hs_type::animation_graph,	"animation_graph" },
		{ e_hs_type::damage_effect,	"damage_effect" },
		{ e_hs_type::object_definition,	"object_definition" },
		{ e_hs_type::bitmap,	"bitmap" },
		{ e_hs_type::shader,	"shader" },
		{ e_hs_type::render_model,	"render model" },
		{ e_hs_type::structure_definition,	"structure definition" },
		{ e_hs_type::lightmap_definition,	"lightmap definition" },
		{ e_hs_type::game_difficulty,	"game_difficulty" },
		{ e_hs_type::team,	"team" },
		{ e_hs_type::actor_type,	"actor_type" },
		{ e_hs_type::hud_corner,	"hud_corner" },
		{ e_hs_type::model_state,	"model_state" },
		{ e_hs_type::network_event,	"network_event" },
		// objects
		{ e_hs_type::object,	"object" },
		{ e_hs_type::unit,	"unit" },
		{ e_hs_type::vehicle,	"vehicle" },
		{ e_hs_type::weapon,	"weapon" },
		{ e_hs_type::device,	"device" },
		{ e_hs_type::scenery,	"scenery" },
		{ e_hs_type::object_name,	"object_name" },
		{ e_hs_type::unit_name,	"unit_name" },
		{ e_hs_type::vehicle_name,	"vehicle_name" },
		{ e_hs_type::weapon_name,	"weapon_name" },
		{ e_hs_type::device_name,	"device_name" },
		{ e_hs_type::scenery_name,	"scenery_name" },
	};

	enum e_hs_function : WORD
	{
		e_hs_function_begin,
		e_hs_function_begin_random,
		e_hs_function_if,
		e_hs_function_cond,
		e_hs_function_set,
		e_hs_function_and,
		e_hs_function_or,
		e_hs_function_plus_equals,
		e_hs_function_subtract,
		e_hs_function_multiply,
		e_hs_function_divide,
		e_hs_function_min,
		e_hs_function_max,
		e_hs_function_equals,
		e_hs_function_not_equal,
		e_hs_function__greater_than,
		e_hs_function_less_than,
		e_hs_function_greater_than_or_equal_to,
		e_hs_function_less_than_or_equal_to,
		e_hs_function_sleep,
		e_hs_function_sleep_forever,
		e_hs_function_sleep_until,
		e_hs_function_wake,
		e_hs_function_inspect,
		e_hs_function_unit,
		e_hs_function_not,
		e_hs_function_pin,
		e_hs_function_print,
		e_hs_function_players,
		e_hs_function_kill_volume_enable,
		e_hs_function_kill_volume_disable,
		e_hs_function_volume_teleport_players_not_inside,
		e_hs_function_volume_test_object,
		e_hs_function_volume_test_objects,
		e_hs_function_volume_test_objects_all,
		e_hs_function_volume_return_objects,
		e_hs_function_volume_return_objects_by_type,
		e_hs_function_list_get,
		e_hs_function_list_count,
		e_hs_function_list_count_not_dead,
		e_hs_function_effect_new,
		e_hs_function_effect_new_on_object_marker,
		e_hs_function_damage_new,
		e_hs_function_damage_object,
		e_hs_function_damage_objects,
		e_hs_function_damage_players,
		e_hs_function_object_create,
		e_hs_function_object_create_clone,
		e_hs_function_object_create_anew,
		e_hs_function_object_create_containing,
		e_hs_function_object_create_clone_containing,
		e_hs_function_object_create_anew_containing,
		e_hs_function_object_destroy,
		e_hs_function_object_destroy_containing,
		e_hs_function_object_destroy_all,
		e_hs_function_object_destroy_type_mask,
		e_hs_function_objects_delete_by_definition,
		e_hs_function_object_hide,
		e_hs_function_object_set_shadowless,
		e_hs_function_object_function_set,
		e_hs_function_object_set_function_variable,
		e_hs_function_object_clear_function_variable,
		e_hs_function_object_clear_all_function_variables,
		e_hs_function_object_dynamic_simulation_disable,
		e_hs_function_object_set_phantom_power,
		e_hs_function_object_wake_physics,
		e_hs_function_object_set_ranged_attack_inhibited,
		e_hs_function_object_set_melee_attack_inhibited,
		e_hs_function_objects_dump_memory,
		e_hs_function_object_get_health,
		e_hs_function_object_get_shield,
		e_hs_function_object_set_shield_effect,
		e_hs_function_object_set_physics,
		e_hs_function_object_get_parent,
		e_hs_function_objects_attach,
		e_hs_function_object_at_marker,
		e_hs_function_objects_detach,
		e_hs_function_object_set_scale,
		e_hs_function_object_set_velocity,
		e_hs_function_object_set_velocity_2,
		e_hs_function_object_set_deleted_when_deactivated,
		e_hs_function_object_copy_player_appearance,
		e_hs_function_object_model_target_destroyed,
		e_hs_function_object_model_targets_destroyed,
		e_hs_function_object_damage_damage_section,
		e_hs_function_object_cannot_die,
		e_hs_function_object_vitality_pinned,
		e_hs_function_garbage_collect_now,
		e_hs_function_garbage_collect_unsafe,
		e_hs_function_garbage_collect_multiplayer,
		e_hs_function_object_cannot_take_damage,
		e_hs_function_object_can_take_damage,
		e_hs_function_object_cinematic_lod,
		e_hs_function_object_cinematic_collision,
		e_hs_function_object_cinematic_visibility,
		e_hs_function_object_uses_cinematic_lighting,
		e_hs_function_cinematic_lighting_set_primary_light,
		e_hs_function_cinematic_lighting_set_secondary_light,
		e_hs_function_cinematic_lighting_set_ambient_light,
		e_hs_function_objects_predict,
		e_hs_function_objects_predict_high,
		e_hs_function_objects_predict_low,
		e_hs_function_object_type_predict_high,
		e_hs_function_object_type_predict_low,
		e_hs_function_object_type_predict,
		e_hs_function_object_teleport,
		e_hs_function_object_set_facing,
		e_hs_function_object_set_shield,
		e_hs_function_object_set_shield_stun,
		e_hs_function_object_set_shield_stun_infinite,
		e_hs_function_object_set_permutation,
		e_hs_function_object_set_region_state,
		e_hs_function_objects_can_see_object,
		e_hs_function_objects_can_see_flag,
		e_hs_function_objects_distance_to_object,
		e_hs_function_objects_distance_to_flag,
		e_hs_function_map_info,
		e_hs_function_position_predict,
		e_hs_function_shader_predict,
		e_hs_function_bitmap_predict,
		e_hs_function_script_recompile,
		e_hs_function_script_doc,
		e_hs_function_help,
		e_hs_function_game_engine_objects,
		e_hs_function_random_range,
		e_hs_function_real_random_range,
		e_hs_function_physics_constants_reset,
		e_hs_function_physics_set_gravity,
		e_hs_function_physics_set_velocity_frame,
		e_hs_function_physics_disable_character_ground_adhesion_forces,
		e_hs_function_havok_debug_start,
		e_hs_function_havok_dump_world,
		e_hs_function_havok_dump_world_close_movie,
		e_hs_function_havok_profile_start,
		e_hs_function_havok_profile_end,
		e_hs_function_havok_reset_allocated_state,
		e_hs_function_breakable_surfaces_enable,
		e_hs_function_breakable_surfaces_reset,
		e_hs_function_recording_play,
		e_hs_function_recording_play_and_delete,
		e_hs_function_recording_play_and_hover,
		e_hs_function_recording_kill,
		e_hs_function_recording_time,
		e_hs_function_render_lights,
		e_hs_function_texture_camera_set_object_marker,
		e_hs_function_texture_camera_off,
		e_hs_function_render_lights_enable_cinematic_shadow,
		e_hs_function_fog_report,
		e_hs_function_fog_report_summary,
		e_hs_function_fog_report_verbose,
		e_hs_function_fog_mode_control,
		e_hs_function_fog_override_off,
		e_hs_function_fog_override_mode,
		e_hs_function_fog_override_mode_off,
		e_hs_function_fog_override_atmospheric_fog,
		e_hs_function_fog_override_atmospheric_fog_off,
		e_hs_function_fog_override_secondary_fog,
		e_hs_function_fog_override_secondary_fog_off,
		e_hs_function_fog_override_sky_fog,
		e_hs_function_fog_override_sky_fog_off,
		e_hs_function_fog_override_planar_fog,
		e_hs_function_fog_override_planar_fog_off,
		e_hs_function_fog_override_planar_fog_plane,
		e_hs_function_fog_override_planar_fog_plane_off,
		e_hs_function_fog_override_planar_max_atmospheric_depth,
		e_hs_function_fog_override_planar_max_atmospheric_depth_off,
		e_hs_function_fog_override_planar_planar_eye_density,
		e_hs_function_fog_override_planar_planar_eye_density_off,
		e_hs_function_fog_override_atmospheric_secondary_blend,
		e_hs_function_fog_override_atmospheric_secondary_blend_off,
		e_hs_function_fog_override_atmospheric_planar_blend,
		e_hs_function_fog_override_atmospheric_planar_blend_off,
		e_hs_function_render_debug_structure_cluster_visibility,
		e_hs_function_render_debug_structure_cluster_fog,
		e_hs_function_render_debug_structure_fog_plane,
		e_hs_function_render_debug_structure_fog_plane_infinite_extent,
		e_hs_function_render_debug_structure_fog_zone,
		e_hs_function_render_debug_structure_fog_zone_floodfill,
		e_hs_function_render_debug_structure_all_fog_planes,
		e_hs_function_render_debug_structure_all_cluster_errors,
		e_hs_function_render_debug_structure_line_opacity,
		e_hs_function_render_debug_structure_text_opacity,
		e_hs_function_render_debug_structure_opacity,
		e_hs_function_render_debug_structure_non_occluded_fog_planes,
		e_hs_function_scenery_animation_start,
		e_hs_function_scenery_animation_start_loop,
		e_hs_function_scenery_animation_start_relative,
		e_hs_function_scenery_animation_start_relative_loop,
		e_hs_function_scenery_animation_start_at_frame,
		e_hs_function_scenery_animation_idle,
		e_hs_function_scenery_get_animation_time,
		e_hs_function_render_effects,
		e_hs_function_unit_can_blink,
		e_hs_function_unit_set_active_camo,
		e_hs_function_unit_open,
		e_hs_function_unit_close,
		e_hs_function_unit_kill,
		e_hs_function_unit_kill_silent,
		e_hs_function_unit_is_emitting,
		e_hs_function_unit_get_custom_animation_time,
		e_hs_function_unit_stop_custom_animation,
		e_hs_function_custom_animation,
		e_hs_function_custom_animation_loop,
		e_hs_function_custom_animation_relative,
		e_hs_function_custom_animation_relative_loop,
		e_hs_function_custom_animation_list,
		e_hs_function_unit_custom_animation_at_frame,
		e_hs_function_unit_is_playing_custom_animation,
		e_hs_function_object_set_custom_animations_hold_on_last_frame,
		e_hs_function_object_set_custom_animations_prevent_lipsync_head_movement,
		e_hs_function_unit_set_actively_controlled,
		e_hs_function_unit_get_team_index,
		e_hs_function_unit_aim_without_turning,
		e_hs_function_unit_set_enterable_by_player,
		e_hs_function_unit_get_enterable_by_player,
		e_hs_function_unit_only_takes_damage_from_players_team,
		e_hs_function_unit_enter_vehicle,
		e_hs_function_unit_board_vehicle,
		e_hs_function_unit_set_emotion,
		e_hs_function_unit_set_emotion_animation,
		e_hs_function_unit_set_emotional_state,
		e_hs_function_unit_enable_eye_tracking,
		e_hs_function_unit_in_vehicle,
		e_hs_function_vehicle_test_seat_list,
		e_hs_function_vehicle_test_seat,
		e_hs_function_unit_set_prefer_tight_camera_track,
		e_hs_function_unit_exit_vehicle,
		e_hs_function_unit_exit_vehicle_2,
		e_hs_function_unit_set_maximum_vitality,
		e_hs_function_units_set_maximum_vitality,
		e_hs_function_unit_set_current_vitality,
		e_hs_function_units_set_current_vitality,
		e_hs_function_vehicle_load_magic,
		e_hs_function_vehicle_unload,
		e_hs_function_unit_set_animation_mode,
		e_hs_function_magic_melee_attack,
		e_hs_function_vehicle_riders,
		e_hs_function_vehicle_driver,
		e_hs_function_vehicle_gunner,
		e_hs_function_unit_get_health,
		e_hs_function_unit_get_shield,
		e_hs_function_unit_get_total_grenade_count,
		e_hs_function_unit_has_weapon,
		e_hs_function_unit_has_weapon_readied,
		e_hs_function_unit_lower_weapon,
		e_hs_function_unit_raise_weapon,
		e_hs_function_unit_animation_forced_seat,
		e_hs_function_unit_doesnt_drop_items,
		e_hs_function_unit_impervious,
		e_hs_function_unit_suspended,
		e_hs_function_unit_add_equipment,
		e_hs_function_weapon_hold_trigger,
		e_hs_function_weapon_enable_warthog_chaingun_light,
		e_hs_function_device_set_never_appears_locked,
		e_hs_function_device_set_power,
		e_hs_function_device_get_power,
		e_hs_function_device_set_position,
		e_hs_function_device_get_position,
		e_hs_function_device_set_position_immediate,
		e_hs_function_device_group_get,
		e_hs_function_device_group_set,
		e_hs_function_device_group_set_immediate,
		e_hs_function_device_one_sided_set,
		e_hs_function_device_operates_automatically_set,
		e_hs_function_device_closes_automatically_set,
		e_hs_function_device_group_change_only_once_more_set,
		e_hs_function_device_set_position_track,
		e_hs_function_device_set_overlay_track,
		e_hs_function_device_animate_position,
		e_hs_function_device_animate_overlay,
		e_hs_function_cheat_all_powerups,
		e_hs_function_cheat_all_weapons,
		e_hs_function_cheat_all_vehicles,
		e_hs_function_cheat_teleport_to_camera,
		e_hs_function_cheat_active_camouflage,
		e_hs_function_cheat_active_camouflage_by_player,
		e_hs_function_cheats_load,
		e_hs_function_drop,
		e_hs_function_ai_enable,
		e_hs_function_ai_enabled,
		e_hs_function_ai_grenades,
		e_hs_function_ai_dialogue_enable,
		e_hs_function_ai_dialogue_log_reset,
		e_hs_function_ai_dialogue_log_dump,
		e_hs_function_ai_get_object,
		e_hs_function_ai_get_unit,
		e_hs_function_ai_attach,
		e_hs_function_ai_attach_units,
		e_hs_function_ai_detach,
		e_hs_function_ai_detach_units,
		e_hs_function_ai_place,
		e_hs_function_ai_place_2,
		e_hs_function_ai_place_in_vehicle,
		e_hs_function_ai_cannot_die,
		e_hs_function_ai_vitality_pinned,
		e_hs_function_ai_overcomes_oversteer,
		e_hs_function_ai_kill,
		e_hs_function_ai_kill_silent,
		e_hs_function_ai_erase,
		e_hs_function_ai_erase_all,
		e_hs_function_ai_disposable,
		e_hs_function_ai_select,
		e_hs_function_ai_deselect,
		e_hs_function_ai_set_deaf,
		e_hs_function_ai_set_blind,
		e_hs_function_ai_magically_see,
		e_hs_function_ai_magically_see_object,
		e_hs_function_ai_set_active_camo,
		e_hs_function_ai_suppress_combat,
		e_hs_function_ai_migrate,
		e_hs_function_ai_allegiance,
		e_hs_function_ai_allegiance_remove,
		e_hs_function_ai_braindead,
		e_hs_function_ai_braindead_by_unit,
		e_hs_function_ai_disregard,
		e_hs_function_ai_prefer_target,
		e_hs_function_ai_teleport_to_starting_location_if_outside_bsp,
		e_hs_function_ai_renew,
		e_hs_function_ai_force_active,
		e_hs_function_ai_force_active_by_unit,
		e_hs_function_ai_playfight,
		e_hs_function_ai_reconnect,
		e_hs_function_ai_berserk,
		e_hs_function_ai_set_team,
		e_hs_function_ai_allow_dormant,
		e_hs_function_ai_is_attacking,
		e_hs_function_ai_fighting_count,
		e_hs_function_ai_living_count,
		e_hs_function_ai_living_fraction,
		e_hs_function_ai_strength,
		e_hs_function_ai_swarm_count,
		e_hs_function_ai_nonswarm_count,
		e_hs_function_ai_actors,
		e_hs_function_ai_allegiance_broken,
		e_hs_function_ai_set_orders,
		e_hs_function_ai_spawn_count,
		e_hs_function_object_get_ai,
		e_hs_function_ai_trigger_test,
		e_hs_function_generate_pathfinding,
		e_hs_function_ai_render_paths_all,
		e_hs_function_ai_vehicle_get,
		e_hs_function_ai_vehicle_get_from_starting_location,
		e_hs_function_ai_vehicle_reserve_seat,
		e_hs_function_ai_vehicle_reserve,
		e_hs_function_ai_vehicle_enter,
		e_hs_function_ai_vehicle_enter_2,
		e_hs_function_ai_vehicle_enter_immediate,
		e_hs_function_ai_vehicle_enter_immediate_2,
		e_hs_function_ai_enter_squad_vehicles,
		e_hs_function_ai_vehicle_exit,
		e_hs_function_ai_vehicle_exit_2,
		e_hs_function_vehicle_overturned,
		e_hs_function_vehicle_flip,
		e_hs_function_ai_combat_status,
		e_hs_function_flock_start,
		e_hs_function_flock_stop,
		e_hs_function_flock_create,
		e_hs_function_flock_delete,
		e_hs_function_ai_verify_tags,
		e_hs_function_ai_wall_lean,
		e_hs_function_ai_play_line,
		e_hs_function_ai_play_line_at_player,
		e_hs_function_ai_play_line_on_object,
		e_hs_function_ai_scene,
		e_hs_function_ai_scene_2,
		e_hs_function_ai_scene_3,
		e_hs_function_cs_run_command_script,
		e_hs_function_cs_queue_command_script,
		e_hs_function_cs_stack_command_script,
		e_hs_function_cs_run_joint_command_script,
		e_hs_function_cs_run_joint_command_script_2,
		e_hs_function_cs_command_script_running,
		e_hs_function_cs_command_script_queued,
		e_hs_function_cs_number_queued,
		e_hs_function_cs_switch,
		e_hs_function_cs_switch_index,
		e_hs_function_cs_transfer,
		e_hs_function_cs_transfer_stack,
		e_hs_function_cs_transfer_queue,
		e_hs_function_cs_fly_to,
		e_hs_function_cs_fly_to_2,
		e_hs_function_cs_fly_to_and_face,
		e_hs_function_cs_fly_to_and_face_2,
		e_hs_function_cs_fly_by,
		e_hs_function_cs_fly_by_2,
		e_hs_function_cs_go_to,
		e_hs_function_cs_go_to_2,
		e_hs_function_cs_go_by,
		e_hs_function_cs_go_by_2,
		e_hs_function_cs_go_to_and_face,
		e_hs_function_cs_start_to,
		e_hs_function_cs_go_to_nearest,
		e_hs_function_cs_moving,
		e_hs_function_cs_look,
		e_hs_function_cs_look_player,
		e_hs_function_cs_look_object,
		e_hs_function_cs_aim,
		e_hs_function_cs_aim_player,
		e_hs_function_cs_aim_object,
		e_hs_function_cs_face,
		e_hs_function_cs_face_player,
		e_hs_function_cs_face_object,
		e_hs_function_cs_move_in_direction,
		e_hs_function_cs_pause,
		e_hs_function_cs_shoot,
		e_hs_function_cs_shoot_2,
		e_hs_function_cs_shoot_point,
		e_hs_function_cs_vehicle_speed,
		e_hs_function_cs_grenade,
		e_hs_function_cs_jump,
		e_hs_function_cs_jump_to_point,
		e_hs_function_cs_vocalize,
		e_hs_function_cs_play_sound,
		e_hs_function_cs_play_sound_2,
		e_hs_function_cs_play_sound_3,
		e_hs_function_cs_stop_sound,
		e_hs_function_cs_custom_animation,
		e_hs_function_cs_stop_custom_animation,
		e_hs_function_cs_play_line,
		e_hs_function_cs_die,
		e_hs_function_cs_teleport,
		e_hs_function_cs_animate,
		e_hs_function_cs_movement_mode,
		e_hs_function_cs_crouch,
		e_hs_function_cs_crouch_2,
		e_hs_function_cs_set_pathfinding_radius,
		e_hs_function_cs_go_to_vehicle,
		e_hs_function_cs_set_behavior,
		e_hs_function_cs_formation,
		e_hs_function_cs_deploy_turret,
		e_hs_function_cs_approach,
		e_hs_function_cs_start_approach,
		e_hs_function_cs_approach_player,
		e_hs_function_cs_start_approach_player,
		e_hs_function_cs_approach_stop,
		e_hs_function_cs_ignore_obstacles,
		e_hs_function_cs_turn_sharpness,
		e_hs_function_cs_vehicle_speed_instantaneous,
		e_hs_function_cs_vehicle_boost,
		e_hs_function_cs_abort_on_alert,
		e_hs_function_cs_abort_on_damage,
		e_hs_function_cs_abort_on_combat_status,
		e_hs_function_cs_enable_targeting,
		e_hs_function_cs_enable_looking,
		e_hs_function_cs_enable_moving,
		e_hs_function_cs_enable_dialogue,
		e_hs_function_cs_suppress_dialogue_global,
		e_hs_function_cs_set_style,
		e_hs_function_cs_force_combat_status,
		e_hs_function_cs_enable_pathfinding_failsafe,
		e_hs_function_camera_control,
		e_hs_function_camera_set,
		e_hs_function_camera_set_relative,
		e_hs_function_camera_set_animation,
		e_hs_function_camera_set_animation_relative,
		e_hs_function_camera_predict_resources_at_frame,
		e_hs_function_camera_predict_resources_at_point,
		e_hs_function_camera_set_first_person,
		e_hs_function_camera_time,
		e_hs_function_camera_set_field_of_view,
		e_hs_function_camera_set_pan,
		e_hs_function_camera_pan,
		e_hs_function_debug_camera_save,
		e_hs_function_debug_camera_load,
		e_hs_function_debug_camera_save_name,
		e_hs_function_debug_camera_load_name,
		e_hs_function_director_debug_camera,
		e_hs_function_game_difficulty_get,
		e_hs_function_game_difficulty_get_real,
		e_hs_function_pvs_set_object,
		e_hs_function_pvs_set_camera,
		e_hs_function_pvs_clear,
		e_hs_function_players_unzoom_all,
		e_hs_function_player_enable_input,
		e_hs_function_player_disable_movement,
		e_hs_function_player_flashlight_on,
		e_hs_function_player_active_camouflage_on,
		e_hs_function_player_camera_control,
		e_hs_function_player_action_test_reset,
		e_hs_function_player_action_test_jump,
		e_hs_function_player_action_test_primary_trigger,
		e_hs_function_player_action_test_grenade_trigger,
		e_hs_function_player_action_test_vision_trigger,
		e_hs_function_player_action_test_zoom,
		e_hs_function_player_action_test_rotate_weapons,
		e_hs_function_player_action_test_rotate_grenades,
		e_hs_function_player_action_test_melee,
		e_hs_function_player_action_test_action,
		e_hs_function_player_action_test_accept,
		e_hs_function_player_action_test_cancel,
		e_hs_function_player_action_test_look_relative_up,
		e_hs_function_player_action_test_look_relative_down,
		e_hs_function_player_action_test_look_relative_left,
		e_hs_function_player_action_test_look_relative_right,
		e_hs_function_player_action_test_look_relative_all_directions,
		e_hs_function_player_action_test_move_relative_all_directions,
		e_hs_function_player_action_test_start,
		e_hs_function_player_action_test_back,
		e_hs_function_player0_looking_up,
		e_hs_function_player0_looking_down,
		e_hs_function_player_action_test_look_up_begin,
		e_hs_function_player_action_test_look_down_begin,
		e_hs_function_player_action_test_look_pitch_end,
		e_hs_function_player_action_test_lookstick_forward,
		e_hs_function_player_action_test_lookstick_backward,
		e_hs_function_debug_teleport_player,
		e_hs_function_map_reset,
		e_hs_function_switch_bsp,
		e_hs_function_switch_bsp_by_name,
		e_hs_function_structure_bsp_index,
		e_hs_function_crash,
		e_hs_function_version,
		e_hs_function_status,
		e_hs_function_record_movie,
		e_hs_function_record_movie_distributed,
		e_hs_function_screenshot,
		e_hs_function_screenshot_big,
		e_hs_function_screenshot_big_jittered,
		e_hs_function_screenshot_cubemap,
		e_hs_function_main_menu,
		e_hs_function_main_halt,
		e_hs_function_map_name,
		e_hs_function_game_multiplayer,
		e_hs_function_game_splitscreen,
		e_hs_function_game_difficulty,
		e_hs_function_game_coop_players,
		e_hs_function_game_initial_bsp,
		e_hs_function_game_tick_rate,
		e_hs_function_game_start,
		e_hs_function_game_rate,
		e_hs_function_texture_cache_flush,
		e_hs_function_geometry_cache_flush,
		e_hs_function_sound_cache_flush,
		e_hs_function_animation_cache_flush,
		e_hs_function_font_cache_flush,
		e_hs_function_texture_cache_test_malloc,
		e_hs_function_debug_memory,
		e_hs_function_debug_memory_by_file,
		e_hs_function_debug_memory_for_file,
		e_hs_function_debug_tags,
		e_hs_function_tags_verify_all,
		e_hs_function_profile_reset,
		e_hs_function_profile_activate,
		e_hs_function_profile_deactivate,
		e_hs_function_profile_mode,
		e_hs_function_collision_log_enable,
		e_hs_function_damage_control_get,
		e_hs_function_damage_control_set,
		e_hs_function_ai_lines,
		e_hs_function_ai_debug_sound_point_set,
		e_hs_function_ai_dialogue_break_on_vocalization,
		e_hs_function_fade_in,
		e_hs_function_fade_out,
		e_hs_function_cinematic_start,
		e_hs_function_cinematic_stop,
		e_hs_function_cinematic_skip_start_internal,
		e_hs_function_cinematic_skip_stop_internal,
		e_hs_function_cinematic_show_letterbox,
		e_hs_function_cinematic_show_letterbox_immediate,
		e_hs_function_cinematic_set_title,
		e_hs_function_cinematic_set_title_delayed,
		e_hs_function_cinematic_suppress_bsp_object_creation,
		e_hs_function_cinematic_subtitle,
		e_hs_function_attract_mode_start,
		e_hs_function_attract_mode_set_seconds,
		e_hs_function_game_won,
		e_hs_function_game_lost,
		e_hs_function_game_revert,
		e_hs_function_game_is_cooperative,
		e_hs_function_game_is_playtest,
		e_hs_function_game_can_use_flashlights,
		e_hs_function_game_save_and_quit,
		e_hs_function_game_save_unsafe,
		e_hs_function_debug_spawning,
		e_hs_function_king_set_hill,
		e_hs_function_core_load,
		e_hs_function_core_load_name,
		e_hs_function_core_save,
		e_hs_function_core_save_name,
		e_hs_function_core_load_game,
		e_hs_function_core_load_game_name,
		e_hs_function_core_regular_upload_to_debug_server,
		e_hs_function_core_set_upload_option,
		e_hs_function_film_play_hack,
		e_hs_function_game_safe_to_save,
		e_hs_function_game_safe_to_speak,
		e_hs_function_game_all_quiet,
		e_hs_function_game_save,
		e_hs_function_game_save_cancel,
		e_hs_function_game_save_no_timeout,
		e_hs_function_game_save_immediate,
		e_hs_function_game_saving,
		e_hs_function_game_reverted,
		e_hs_function_sound_set_tag_parameter_unsafe,
		e_hs_function_sound_impulse_predict,
		e_hs_function_sound_impulse_trigger,
		e_hs_function_sound_impulse_start,
		e_hs_function_sound_impulse_start_cinematic,
		e_hs_function_sound_impulse_start_effect,
		e_hs_function_sound_impulse_time,
		e_hs_function_sound_impulse_time_2,
		e_hs_function_sound_impulse_language_time,
		e_hs_function_sound_impulse_stop,
		e_hs_function_sound_impulse_start_3d,
		e_hs_function_sound_looping_predict,
		e_hs_function_sound_looping_start,
		e_hs_function_sound_looping_stop,
		e_hs_function_sound_looping_stop_immediately,
		e_hs_function_sound_looping_set_scale,
		e_hs_function_sound_looping_set_alternate,
		e_hs_function_sound_loop_spam,
		e_hs_function_sound_class_show_channel,
		e_hs_function_sound_class_debug_sound_start,
		e_hs_function_debug_sounds_enable,
		e_hs_function_sound_class_set_gain,
		e_hs_function_sound_class_set_gain_db,
		e_hs_function_sound_class_enable_ducker,
		e_hs_function_debug_sound_environment_parameter,
		e_hs_function_sound_set_global_effect,
		e_hs_function_sound_set_global_effect_scale,
		e_hs_function_sound_set_trace_callback_level,
		e_hs_function_sound_dump_miles_debug,
		e_hs_function_vehicle_hover,
		e_hs_function_vehicle_count_bipeds_killed,
		e_hs_function_biped_ragdoll,
		e_hs_function_hud_cinematic_fade,
		e_hs_function_show_hud,
		e_hs_function_show_hud_help_text,
		e_hs_function_show_hud_messages,
		e_hs_function_enable_hud_help_flash,
		e_hs_function_hud_help_flash_restart,
		e_hs_function_hud_show_training_text,
		e_hs_function_hud_set_training_text,
		e_hs_function_hud_enable_training,
		e_hs_function_player_training_activate_flashlight,
		e_hs_function_player_training_activate_crouch,
		e_hs_function_player_training_activate_stealth,
		e_hs_function_activate_nav_point_flag,
		e_hs_function_activate_nav_point_object,
		e_hs_function_activate_team_nav_point_flag,
		e_hs_function_activate_team_nav_point_object,
		e_hs_function_deactivate_nav_point_flag,
		e_hs_function_deactivate_nav_point_object,
		e_hs_function_deactivate_team_nav_point_flag,
		e_hs_function_deactivate_team_nav_point_object,
		e_hs_function_cls,
		e_hs_function_error_overflow_suppression,
		e_hs_function_error_geometry_show,
		e_hs_function_error_geometry_hide,
		e_hs_function_error_geometry_show_all,
		e_hs_function_error_geometry_hide_all,
		e_hs_function_error_geometry_list,
		e_hs_function_player_effect_set_max_translation,
		e_hs_function_player_effect_set_max_rotation,
		e_hs_function_player_effect_set_max_rumble,
		e_hs_function_player_effect_start,
		e_hs_function_player_effect_stop,
		e_hs_function_hud_show_health,
		e_hs_function_hud_blink_health,
		e_hs_function_hud_show_shield,
		e_hs_function_hud_blink_shield,
		e_hs_function_hud_show_motion_sensor,
		e_hs_function_hud_blink_motion_sensor,
		e_hs_function_hud_show_crosshair,
		e_hs_function_hud_show_ammo,
		e_hs_function_hud_clear_messages,
		e_hs_function_hud_set_help_text,
		e_hs_function_hud_set_objective_text,
		e_hs_function_hud_set_timer_time,
		e_hs_function_hud_set_timer_warning_time,
		e_hs_function_hud_set_timer_position,
		e_hs_function_show_hud_timer,
		e_hs_function_pause_hud_timer,
		e_hs_function_hud_get_timer_ticks,
		e_hs_function_time_code_show,
		e_hs_function_time_code_start,
		e_hs_function_time_code_reset,
		e_hs_function_rasterizer_profile_include,
		e_hs_function_rasterizer_profile_include_all,
		e_hs_function_rasterizer_profile_include_all_except,
		e_hs_function_rasterizer_profile_exclude,
		e_hs_function_rasterizer_profile_exclude_all,
		e_hs_function_rasterizer_profile_exclude_all_except,
		e_hs_function_rasterizer_debug_display_bitmap,
		e_hs_function_rasterizer_decals_flush,
		e_hs_function_rasterizer_lens_flares_clear_for_frame,
		e_hs_function_rasterizer_test_screen,
		e_hs_function_rasterizer_test_screen_supablur,
		e_hs_function_rasterizer_test_screen_off,
		e_hs_function_rasterizer_f2,
		e_hs_function_rasterizer_f3,
		e_hs_function_rasterizer_f4,
		e_hs_function_rasterizer_f5,
		e_hs_function_rasterizer_f6,
		e_hs_function_rasterizer_decal_depth_bias,
		e_hs_function_rasterizer_decal_depth_bias_slope_scale,
		e_hs_function_rasterizer_hud_ten_foot,
		e_hs_function_rasterizer_blur,
		e_hs_function_rasterizer_solid_model_color,
		e_hs_function_rasterizer_solid_structure_color,
		e_hs_function_rasterizer_solid_structure_instanced_geometry_color,
		e_hs_function_rasterizer_solid_sky_color,
		e_hs_function_rasterizer_solid_decorator_color,
		e_hs_function_rasterizer_solid_decorator_model_color,
		e_hs_function_rasterizer_solid_decorator_decal_color,
		e_hs_function_rasterizer_solid_decorator_sprite_color,
		e_hs_function_decorator_rebuild_all,
		e_hs_function_script_screen_effect_set_value,
		e_hs_function_cinematic_screen_effect_start,
		e_hs_function_cinematic_screen_effect_set_depth_of_field,
		e_hs_function_cinematic_screen_effect_set_crossfade,
		e_hs_function_cinematic_screen_effect_set_crossfade2,
		e_hs_function_cinematic_screen_effect_stop,
		e_hs_function_cinematic_set_near_clip_distance,
		e_hs_function_cinematic_set_far_clip_distance,
		e_hs_function_cinematic_set_environment_map_attenuation,
		e_hs_function_cinematic_set_environment_map_bitmap,
		e_hs_function_cinematic_reset_environment_map_bitmap,
		e_hs_function_cinematic_set_environment_map_tint,
		e_hs_function_cinematic_reset_environment_map_tint,
		e_hs_function_cinematic_layer,
		e_hs_function_cinematic_dynamic_reflections,
		e_hs_function_lightmaps_expose,
		e_hs_function_player_profile_create,
		e_hs_function_player_profile_create_corrupt,
		e_hs_function_player_has_skills,
		e_hs_function_player_has_mad_secret_skills,
		e_hs_function_controller_invert_look,
		e_hs_function_controller_look_speed,
		e_hs_function_controller_set_look_invert,
		e_hs_function_controller_get_look_invert,
		e_hs_function_controller_unlock_solo_levels,
		e_hs_function_user_interface_controller_get_last_level_played,
		e_hs_function_ui_load_main_menu,
		e_hs_function_ui_text_bounds,
		e_hs_function_ui_show_title_safe_bounds,
		e_hs_function_ui_element_bounds,
		e_hs_function_ui_screen_tag,
		e_hs_function_ui_transition_out_console_window,
		e_hs_function_ui_show_screen_tag_path,
		e_hs_function_ui_show_current_screen_tag,
		e_hs_function_ui_set_beta,
		e_hs_function_ui_memory_dump,
		e_hs_function_ui_set_automation_mode,
		e_hs_function_ui_set_automation_hopper_type,
		e_hs_function_ui_set_automation_variant_type_and_map,
		e_hs_function_ui_set_automation_desired_local_user_count,
		e_hs_function_ui_set_automation_desired_desired_network_game_player_count,
		e_hs_function_ui_set_automation_desired_network_game_length_seconds,
		e_hs_function_ui_set_automation_desired_network_session_name,
		e_hs_function_ui_set_automation_desired_controller_team,
		e_hs_function_ui_set_automation_desired_controller_player_profile,
		e_hs_function_objectives_clear,
		e_hs_function_objectives_show_up_to,
		e_hs_function_objectives_finish_up_to,
		e_hs_function_input_suppress_vibration,
		e_hs_function_update_remote_camera,
		e_hs_function_net_status_filter,
		e_hs_function_net_sim_reset,
		e_hs_function_net_sim_spike_now,
		e_hs_function_net_sim_dropspike_now,
		e_hs_function_net_ping,
		e_hs_function_net_channel_loopback,
		e_hs_function_net_channel_delete,
		e_hs_function_net_leave_squad,
		e_hs_function_net_delegate_host,
		e_hs_function_net_delegate_leader,
		e_hs_function_net_map_name,
		e_hs_function_net_campaign_difficulty,
		e_hs_function_net_player_color,
		e_hs_function_net_reset_objects,
		e_hs_function_net_fatal_error,
		e_hs_function_net_matchmaking_hopper_list,
		e_hs_function_net_matchmaking_hopper_print,
		e_hs_function_net_matchmaking_hopper_set_game,
		e_hs_function_net_set_machine_name,
		e_hs_function_net_event_display_category,
		e_hs_function_net_event_log_category,
		e_hs_function_net_event_list_categories,
		e_hs_function_online_task_list,
		e_hs_function_play_bink_movie,
		e_hs_function_play_credits,
		e_hs_function_bink_time,
		e_hs_function_set_global_doppler_factor,
		e_hs_function_set_global_mixbin_headroom,
		e_hs_function_debug_sound_environment_source_parameter,
		e_hs_function_data_mine_set_mission_segment,
		e_hs_function_data_mine_display_mission_segment,
		e_hs_function_data_mine_insert,
		e_hs_function_data_mine_upload,
		e_hs_function_data_mine_playback,
		e_hs_function_data_mine_playback_last,
		e_hs_function_data_mine_playback_exit,
		e_hs_function_data_mine_enable,
		e_hs_function_data_mine_track_event,
		e_hs_function_data_mine_display_event,
		e_hs_function_data_mine_show_all_events,
		e_hs_function_data_mine_show_tracked_events,
		e_hs_function_data_mine_show_displayed_events,
		e_hs_function_data_mine_display_session_data,
		e_hs_function_data_mine_display_disk_writes,
		e_hs_function_data_mine_debug_menu_setting,
		e_hs_function_data_mine_open_debug_menu,
		e_hs_function_error_enable,
		e_hs_function_render_layer_enable,
		e_hs_function_render_layer_enable_all,
		e_hs_function_rasterizer_overdraw_z,
		e_hs_function_rasterizer_overdraw,
		e_hs_function_rasterizer_layers_overdraw_z,
		e_hs_function_rasterizer_layers_overdraw,
		e_hs_function_test_memory_allocators,
		e_hs_function_test_memory_allocators2,
		e_hs_function_display_video_standard,
		e_hs_function_test_xcr_monkey_enable,
		e_hs_function_test_web_map_snapshot,
		e_hs_function_test_telnet_status_enable,
		e_hs_function_test_telnet_status_interval,
		e_hs_function_webstats_disable,
		e_hs_function_webstats_submit,
		e_hs_function_netdebug_prefer_internet,
		e_hs_function_script_temporary_disable_lightmap_shadows,
		e_hs_function_flag_new,
		e_hs_function_flag_new_at_look,
		e_hs_function_flags_clear,
		e_hs_function_flags_save,
		e_hs_function_flags_save_filtered,
		e_hs_function_flags_save_named,
		e_hs_function_flags_save_named_filtered,
		e_hs_function_flags_default_name,
		e_hs_function_flags_default_comment,
		e_hs_function_flags_set_filter,
		e_hs_function_flags_export,
		e_hs_function_flags_export_filtered,
		e_hs_function_flags_export_named,
		e_hs_function_flags_export_named_filtered,
		e_hs_function_bug_now,
		e_hs_function_bug_now_lite,
		e_hs_function_bug_now_auto,
		e_hs_function_object_list_children,
		e_hs_function_voice_set_outgoing_channel_count,
		e_hs_function_voice_set_voice_repeater_peer_index,
		e_hs_function_net_leaderboard_clear,
		e_hs_function_net_leaderboard_set,
		e_hs_function_dump_loaded_tags,
		e_hs_function_interpolator_start,
		e_hs_function_interpolator_start_smooth,
		e_hs_function_interpolator_stop,
		e_hs_function_interpolator_restart,
		e_hs_function_interpolator_is_active,
		e_hs_function_interpolator_is_finished,
		e_hs_function_interpolator_set_current_value,
		e_hs_function_interpolator_get_current_value,
		e_hs_function_interpolator_get_start_value,
		e_hs_function_interpolator_get_final_value,
		e_hs_function_interpolator_get_current_phase,
		e_hs_function_interpolator_get_current_time_fraction,
		e_hs_function_interpolator_get_start_time,
		e_hs_function_interpolator_get_final_time,
		e_hs_function_interpolator_evaluate_at,
		e_hs_function_interpolator_evaluate_at_time_fraction,
		e_hs_function_interpolator_evaluate_at_time,
		e_hs_function_interpolator_evaluate_at_time_delta,
		e_hs_function_interpolator_stop_all,
		e_hs_function_interpolator_restart_all,
		e_hs_function_interpolator_flip,
		e_hs_function_weather_start,
		e_hs_function_weather_stop,
		e_hs_function_weather_change_intensity,
		e_hs_function_animation_cache_stats_reset,
		e_hs_function_cinematic_clone_players_weapon,
		e_hs_function_cinematic_move_attached_objects,
		e_hs_function_vehicle_enable_ghost_effects,
		e_hs_function_ice_cream_flavor_stock,
		e_hs_function_ice_cream_flavor_available,
		e_hs_function_set_global_sound_environment,
		e_hs_function_reset_dsp_image,
		e_hs_function_game_save_cinematic_skip,
		e_hs_function_cinematic_outro_start,
		e_hs_function_cinematic_enable_ambience_details,
		e_hs_function_set_rasterizer_gamma,
		e_hs_function_predict_model_section,
		e_hs_function_predict_structure_section,
		e_hs_function_predict_lightmap_bucket,
		e_hs_function_predict_bitmap,
		e_hs_function_get_prediction_offset,
		e_hs_function_rasterizer_bloom_override,
		e_hs_function_rasterizer_bloom_override_reset,
		e_hs_function_rasterizer_bloom_override_blur_amount,
		e_hs_function_rasterizer_bloom_override_threshold,
		e_hs_function_rasterizer_bloom_override_brightness,
		e_hs_function_rasterizer_bloom_override_box_factor,
		e_hs_function_rasterizer_bloom_override_max_factor,
		e_hs_function_rasterizer_bloom_override_silver_bullet,
		e_hs_function_rasterizer_bloom_override_only,
		e_hs_function_rasterizer_bloom_override_high_res,
		e_hs_function_rasterizer_bloom_override_brightness_alpha,
		e_hs_function_rasterizer_bloom_override_max_factor_alpha,
		e_hs_function_cache_block_for_one_frame,
		e_hs_function_sound_suppress_ambience_update_on_revert,
		e_hs_function_ui_error_ok,
		e_hs_function_ui_error_ok_cancel,
		e_hs_function_ui_confirmation,
		e_hs_function_cinematic_lightmap_shadow_disable,
		e_hs_function_cinematic_lightmap_shadow_enable,
		e_hs_function_predict_animation,
		e_hs_function_online_message_send,
		e_hs_function_test_web_event_local_cheater,
		e_hs_function_test_web_event_remote_cheater,
		e_hs_function_test_cheating_detect,
		e_hs_function_test_network_storage_simulate,
		e_hs_function_scenario_dump_scenario_signature_enable,
		e_hs_function_scenario_force_signature_failure_enable,
		e_hs_function_scenario_force_name_failure_enable,
		e_hs_function_scenario_ignore_failures_enable,
		e_hs_function_scenario_dump_scenario_signature_disable,
		e_hs_function_scenario_force_signature_failure_disable,
		e_hs_function_scenario_force_name_failure_disable,
		e_hs_function_scenario_ignore_failures_disable,
		e_hs_function_hs_unk_1,
		e_hs_function_hs_unk_2,
		e_hs_function_hs_unk_3,
		e_hs_function_hs_unk_4,
		e_hs_function_loading_screen_fade_to_white,
		e_hs_function_rasterizer_debug_frame_usage,
		e_hs_function_rasterizer_debug_crap_pixel_shader,
		e_hs_function_enable_render_light_suppressor,
		e_hs_function_disable_render_light_suppressor
	};

	const e_hs_function hs_sync_table[HS_SYNC_TABLE_SIZE]
	{
		e_hs_function_fade_out,
		e_hs_function_fade_in,
		e_hs_function_print,
		e_hs_function_player_enable_input,
		e_hs_function_camera_control,
		e_hs_function_ai_allegiance,
		e_hs_function_sound_impulse_start,
		e_hs_function_ai_play_line_on_object,
		e_hs_function_camera_set_animation_relative,
		e_hs_function_cinematic_start,
		e_hs_function_cinematic_stop,
		e_hs_function_custom_animation_relative,
		//e_hs_function_object_cinematic_lod,
		e_hs_function_device_animate_position,
		e_hs_function_device_set_position_track,
		e_hs_function_switch_bsp,
		e_hs_function_switch_bsp_by_name
	};

	struct HaloScriptGlobal
	{
		e_hs_type type;
		BYTE padding[2];
		void* data;
	};

	typedef void** (__cdecl* hs_func_impl)(int hs_opcode, void* script_engine, char a3);

	struct HaloScriptCommand
	{
		e_hs_type type;
		WORD unk;
		hs_func_impl func;
		char* usage;
		WORD arg_count;
		e_hs_type arg_array[1]; // array size is dynamic, but always at least one
	};

	struct s_networked_hs_function
	{
		hs::e_hs_function function_type;
		char arg_buffer[HS_SENT_BUFFER_SIZE];
	};

	struct s_hs_fade_args
	{
		real_color_rgb color;
		__int16 ticks;
	};

	struct s_hs_sound_impulse_start_args
	{
		char* sound;
		datum object;
		float scale;
	};

	struct s_hs_ai_play_line_on_object_args
	{
		datum object;
		char* sound;
	};

	struct s_hs_camera_set_animation_relative_args
	{
		char* animation_path;
		char* animation;
		int unit; 
		WORD cutscene_flag_index;
	};
	
	struct s_hs_custom_animation_relative_args
	{
		datum object;
		datum animation_path;
		string_id animation;
		bool interpolates_into_animation;
		datum relative_object;
	};

	struct s_hs_object_cinematic_lod_args
	{
		datum object; 
		bool enable;
	};

	struct s_hs_device_animate_position_args
	{
		datum device;
		float position; 
		float time; 
		float unk1; 
		float unk2; 
		bool interpolate;
	};
	
	struct s_hs_device_set_position_track_args
	{
		datum device;
		string_id animation;
		float interpolation_time;
	};

	void UnitKill(datum unitDatum);
	bool UnitInVehicle(datum unitDatum);
	float UnitGetHealth(datum unitDatum);
	float UnitGetShield(datum unitDatum);

	void PhysicsSetGravity(float Multiplier);
	void PhysicsSetVelocityFrame(float unk1, float unk2, float unk3);
	void RenderLightsEnableCinenaticShadow(bool unk1, datum objectDatum, string_id StringId, float unk2);
	void ObjectDestroy(datum object_datum_index);
	void __cdecl print_to_console(const char* output);

	void CallNetworkedHSFunction(const s_networked_hs_function* data);
	void Initialize();
}
